server:
  port: 8111
  servlet:
    context-path: /bokee

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bokee?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
  redis:
    host: 127.0.0.1
    password: 123456

logging:
  level:
    com.chaincat.bokee.dao.mapper: DEBUG

aspect:
  log:
    exclude-params: 'content'